### ISSUE TITLE
Changing Skill Attributes

### ISSUE THREAD

**Issue by Cup-of-Coffee** [fvtt-fria-ligan/twilight2000-foundry-vtt#121]
### Description

When using the Twilight 2000 system I would like to see the attributes for skills to be able to be changed for a different attribute. 

In the base rules for example, Heavy Weapons could use ``STR``, ``AGI`` or ``INT`` for certain weapons.

### Suggested solution

Have the option to exchange the attribute for a skill in the skill sheet.

### Alternative

Have a drop-down menu in the Stats tab between ``Rating`` and ``Base Die`` for each skill that changes the attribute.

### Validations

- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Stefouch** [comment]
In the item sheet, there are already two fields you can use to define which attribute and skill to use with that item.

Just click the item in the character's inventory to roll the dice for the chosen attribute and skill.

If you want to roll a straight Heavy weapon skill with no item, you can make a macro too.

I won't make the suggested change because:

1. The `Heavy Weapon` skill is listed under the `STR` attribute in the official character sheet.
2. Could confuse the players
3. There is already a solution in the item sheet
4. Too much code work _(it looks simple, but it would need a lot of core changes)_

Still, if you want to enforce which attribute is related to which skill, there is a workaround: You can change the Skills Map config by creating your own world script or a small module that change the following:

```js
CONFIG.T2K4E.skillsMap.heavyWeapons = 'int'
```

This line with move the `Heavy Weapons` skill under the `Intelligence` attribute.
