### ISSUE TITLE
Journal text is formatting incorrectly

### ISSUE THREAD

**Issue by Kosmonautilus** [fvtt-fria-ligan/twilight2000-foundry-vtt#130]
### Describe the bug

The formatting for journal entries in Foundry V10.291 and T2K V10.1.0 seems to be bugging out invariably. The things I've noticed are as follows:

- Unusual indentation with paragraph style text: The first line will indent once, then the rest will indent twice. Text will also indent more than twice at certain points (seemingly after a paragraph) but I can't seem to reproduce it. <img src="https://user-images.githubusercontent.com/20175813/227862041-fb8d2a7c-4ae1-4ce3-aa48-afc117dc720b.png" width="500">
- Other text styles (I noticed it mainly in code blocks) have a space before their text that cannot be removed.

### Reproduction

1. Create a journal entry.
2. Edit it and add text and/or change the stylings.

### System Info

```sh
Game Version: Foundry 10.291
System Version: T2K 10.1.0

Client: Foundry Desktop App
OS: Windows
```

### Priority this issue should have?

Low (formatting issues, things that don't impact operation)

### Validations

- [X] Done a clean install of the system.
- [X] Disabled all modules.
- [X] Checked if the issue is present in a new world instance (create a new world in foundry using the Twilight 2000 system).

**Comment by Stefouch** [comment]
There is an indentation for each paragraph following an other.

1. Typing <kbd>⏎ ENTER</kbd> will create a new paragraph (with the adverse effect to add an indent due to how the styles are coded.
2. Instead, type <kbd>⇧ Shift</kbd> + <kbd>⏎ Enter</kbd> to create a new line (carriage return) (html code: `</br>`)

Another solution:
You can remove that indentation with the Custom CSS module, or edit the HTML code of your journal entry (`</>` button) like the following:
```htm
<p>My first paragraph</p>
<p>My second paragraph with an indent</p>
<p style="text-indent: 0">My third paragraph with no indent</p>
```

**Comment by Kosmonautilus** [comment]
Yeah, I found that it was intentional in the CSS and went ahead and removed
it to match up with the style I was going for in my instance.
